# ----------------------------
# Bad Apple Player - SD card loader
# ----------------------------

NAME=badapple

LDHAS_ARG_PROCESSING = 1
LDHAS_EXIT_HANDLER = 0

AGONDEV_TOOLCHAIN = /Users/alice/dev/agondev/agondev

# ----------------------------
include $(AGONDEV_TOOLCHAIN)/config/makefile.inc
