# ----------------------------
# Cube Player - C implementation
# ----------------------------

NAME=vivid

LDHAS_ARG_PROCESSING = 0
LDHAS_EXIT_HANDLER = 0

AGONDEV_TOOLCHAIN = /Users/alice/dev/agondev/agondev

# ----------------------------
include $(AGONDEV_TOOLCHAIN)/config/makefile.inc
