# ----------------------------
# bbplay - bytebeat music player
# Usage: bbplay <1-4>
# ----------------------------

NAME=bbplay

LDHAS_ARG_PROCESSING = 1
LDHAS_EXIT_HANDLER = 0

AGONDEV_TOOLCHAIN = /Users/alice/dev/agondev/agondev

# ----------------------------
include $(AGONDEV_TOOLCHAIN)/config/makefile.inc
