#!/usr/bin/env python3
"""Build a MOS .bin binary for the spinning cube demo.

Two-step process:
  1. Python generates VDU frame data → cube_frames.bin (raw blob)
  2. ez80asm assembles cube.asm (which INCBINs the blob) → cube.bin

Usage:
  python build_cube_bin.py [--frames 360] [--fps 30]
  # Outputs: cube.bin (ready to RUN on Agon)
"""

import argparse
import math
import os
import struct
import subprocess
import sys
import time

import numpy as np

from gen_cube import (
    make_cube_mesh, rotation_matrix, generate_frame,
)

EZ80ASM = os.environ.get("EZ80ASM", "/Users/alice/dev/bin/ez80asm")
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))


def generate_all_frames(num_frames):
    """Generate all cube VDU frame byte blobs."""
    vertices, triangles, face_ids = make_cube_mesh()
    frames = []
    for i in range(num_frames):
        angle_y = 2 * math.pi * i / num_frames
        angle_x = 0.3 * math.sin(2 * math.pi * i / num_frames * 2)
        rot = rotation_matrix(angle_x, angle_y)
        vdp_stream, _canvas = generate_frame(vertices, triangles, face_ids, rot)
        frames.append(vdp_stream.get_bytes())
    return frames


def export_frame_blob(frames, blob_path):
    """Export frame data as a binary blob.

    Format: [num_frames:u16-LE] then for each frame [len:u16-LE][vdu_bytes...]
    """
    with open(blob_path, "wb") as f:
        f.write(struct.pack("<H", len(frames)))
        for frame_bytes in frames:
            f.write(struct.pack("<H", len(frame_bytes)))
            f.write(frame_bytes)

    total = os.path.getsize(blob_path)
    print(f"[build] Wrote frame blob: {total:,} bytes to {blob_path}",
          file=sys.stderr)
    return total


def export_setup_blob(setup_path):
    """Export VDU setup sequence as a binary blob."""
    setup = bytearray()
    setup.extend([22, 8])           # VDU 22, 8 — mode 8 (320x240, 64 colours)
    setup.extend([23, 0, 0xC0, 0])  # pixel coordinates (top-left origin, Y down)
    setup.extend([23, 1, 0])        # cursor off
    setup.append(12)                # CLS
    setup.append(16)                # CLG

    with open(setup_path, "wb") as f:
        f.write(setup)
    print(f"[build] Wrote setup blob: {len(setup)} bytes to {setup_path}",
          file=sys.stderr)
    return len(setup)


def generate_asm(num_frames, setup_len, wait_ticks):
    """Generate the eZ80 assembly source."""
    return f"""\
;
; cube.asm — Spinning cube MOS executable
; Auto-generated by build_cube_bin.py
;
; Assembled with: ez80asm cube.asm cube.bin
;

\t\t\t.ASSUME\tADL = 1

\t\t\tJP\t_start\t\t\t; Jump over header

_exec_name:\t\tDB\t"cube.bin",0\t\t; Executable name

\t\t\tALIGN\t64

\t\t\tDB\t"MOS"\t\t\t; MOS magic
\t\t\tDB\t00h\t\t\t; Header version 0
\t\t\tDB\t01h\t\t\t; ADL mode

_start:
\t\t\tPUSH\tAF
\t\t\tPUSH\tBC
\t\t\tPUSH\tDE
\t\t\tPUSH\tIX
\t\t\tPUSH\tIY

\t\t\tLD\tA, MB\t\t\t; Save MB
\t\t\tPUSH\tAF
\t\t\tXOR\tA
\t\t\tLD\tMB, A\t\t\t; Clear MB for 24-bit MOS API

\t\t\t; Get system variables pointer
\t\t\tLD\tA, 08h\t\t\t; mos_sysvars
\t\t\tRST.LIL\t08h\t\t\t; IX = sysvars

\t\t\t; Send VDU setup (mode 8, pixel coords, cursor off, CLS, CLG)
\t\t\tLD\tHL, setup_data
\t\t\tLD\tBC, {setup_len}
\t\t\tRST.LIL\t18h\t\t\t; Send BC bytes from HL to VDP

\t\t\t; Wait for mode switch to settle
\t\t\tLD\tB, 15
\t\t\tCALL\twait_ticks

; ---- Main animation loop (infinite) ----
main_loop:
\t\t\tLD\tHL, frame_data + 2\t; Skip num_frames u16 header
\t\t\tLD\tDE, {num_frames}

next_frame:
\t\t\t; Read frame length: 16-bit LE at (HL)
\t\t\tLD\tC, (HL)
\t\t\tINC\tHL
\t\t\tLD\tB, (HL)
\t\t\tINC\tHL\t\t\t; HL = frame VDU data start

\t\t\tPUSH\tDE\t\t\t; save frame counter
\t\t\tPUSH\tHL\t\t\t; save data pointer
\t\t\tPUSH\tBC\t\t\t; save frame length

\t\t\t; Send frame to VDP
\t\t\tRST.LIL\t18h\t\t\t; HL=addr, BC=len

\t\t\t; Wait {wait_ticks} vsync ticks (~{60 // wait_ticks}fps)
\t\t\tLD\tB, {wait_ticks}
\t\t\tCALL\twait_ticks

\t\t\t; Check for space key (sysvar_keyascii = IX+5)
\t\t\tLD\tA, (IX+5)
\t\t\tCP\t20h\t\t\t; space?
\t\t\tJR\tZ, _exit

\t\t\tPOP\tBC\t\t\t; restore frame length
\t\t\tPOP\tHL\t\t\t; restore data pointer
\t\t\tPOP\tDE\t\t\t; restore frame counter

\t\t\t; Advance HL past frame data
\t\t\tADD\tHL, BC

\t\t\t; Decrement frame counter, loop if not zero
\t\t\tDEC\tDE
\t\t\tLD\tA, D
\t\t\tOR\tE
\t\t\tJR\tNZ, next_frame

\t\t\t; Loop forever
\t\t\tJP\tmain_loop

_exit:
\t\t\tPOP\tBC\t\t\t; clean up stack from frame loop
\t\t\tPOP\tHL
\t\t\tPOP\tDE

\t\t\t; Restore mode 0 + cursor
\t\t\tLD\tHL, restore_data
\t\t\tLD\tBC, 5
\t\t\tRST.LIL\t18h

\t\t\tPOP\tAF
\t\t\tLD\tMB, A\t\t\t; Restore MB
\t\t\tPOP\tIY
\t\t\tPOP\tIX
\t\t\tPOP\tDE
\t\t\tPOP\tBC
\t\t\tPOP\tAF
\t\t\tRET

; ---- Subroutine: wait B ticks of sysvar_time ----
; sysvar_time (IX+0) increments by 2 every VBLANK (~60Hz).
; We wait for B changes of the low byte.
wait_ticks:
wt_outer:
\t\t\tLD\tA, (IX+0)\t\t; current sysvar_time low byte
\t\t\tLD\tC, A\t\t\t; snapshot
wt_inner:
\t\t\tLD\tA, (IX+0)\t\t; re-read
\t\t\tCP\tC\t\t\t; changed?
\t\t\tJR\tZ, wt_inner\t\t; no — keep spinning
\t\t\tDJNZ\twt_outer\t\t; yes — one tick done
\t\t\tRET

; ---- Data ----
setup_data:
\t\t\tINCBIN\t"cube_setup.bin"

restore_data:
\t\t\tDB\t22, 0\t\t\t; VDU 22, 0 — mode 0
\t\t\tDB\t23, 1, 1\t\t; cursor on

frame_data:
\t\t\tINCBIN\t"cube_frames.bin"
"""


def main():
    parser = argparse.ArgumentParser(
        description="Build spinning cube MOS .bin binary")
    parser.add_argument("-o", "--output", type=str, default="cube.bin",
                        help="Output .bin file (default: cube.bin)")
    parser.add_argument("--frames", type=int, default=360,
                        help="Number of animation frames (default: 360)")
    parser.add_argument("--fps", type=int, default=30,
                        help="Target FPS — controls vsync wait (default: 30)")
    args = parser.parse_args()

    ticks = max(1, 60 // args.fps)

    # Step 1: Generate VDU frame data
    print(f"[build] Generating {args.frames} frames of spinning cube...",
          file=sys.stderr)
    t0 = time.time()
    frames = generate_all_frames(args.frames)
    elapsed = time.time() - t0

    total_vdu = sum(len(f) for f in frames)
    min_size = min(len(f) for f in frames)
    max_size = max(len(f) for f in frames)
    print(f"[build] Generated in {elapsed:.1f}s — "
          f"{total_vdu:,} bytes VDU data "
          f"(per frame: {min_size}-{max_size}B)",
          file=sys.stderr)

    # Step 2: Export binary blobs
    frames_blob = os.path.join(SCRIPT_DIR, "cube_frames.bin")
    setup_blob = os.path.join(SCRIPT_DIR, "cube_setup.bin")
    export_frame_blob(frames, frames_blob)
    setup_len = export_setup_blob(setup_blob)

    # Step 3: Generate assembly source
    asm_src = os.path.join(SCRIPT_DIR, "cube.asm")
    asm_code = generate_asm(args.frames, setup_len, ticks)
    with open(asm_src, "w") as f:
        f.write(asm_code)
    print(f"[build] Wrote assembly source: {asm_src}", file=sys.stderr)

    # Step 4: Assemble with ez80asm
    out_bin = os.path.join(SCRIPT_DIR, args.output)
    cmd = [EZ80ASM, asm_src, out_bin, "-l", "-x"]
    print(f"[build] Running: {' '.join(cmd)}", file=sys.stderr)
    result = subprocess.run(cmd, capture_output=True, text=True)
    print(result.stdout, end="", file=sys.stderr)
    if result.stderr:
        print(result.stderr, end="", file=sys.stderr)
    if result.returncode != 0:
        print(f"[build] ERROR: ez80asm failed with code {result.returncode}",
              file=sys.stderr)
        sys.exit(1)

    bin_size = os.path.getsize(out_bin)
    print(f"[build] Success! {bin_size:,} bytes → {out_bin}", file=sys.stderr)

    # Copy to sdcard
    sdcard = "/Users/alice/dev/fab-agon-emulator/sdcard"
    if os.path.isdir(sdcard):
        import shutil
        dest = os.path.join(sdcard, "cube.bin")
        shutil.copy2(out_bin, dest)
        print(f"[build] Copied to {dest}", file=sys.stderr)


if __name__ == "__main__":
    main()
