;
; cube.asm — Spinning cube MOS executable
; Auto-generated by build_cube_bin.py
;
; Assembled with: ez80asm cube.asm cube.bin
;

			.ASSUME	ADL = 1

			JP	_start			; Jump over header

_exec_name:		DB	"cube.bin",0		; Executable name

			ALIGN	64

			DB	"MOS"			; MOS magic
			DB	00h			; Header version 0
			DB	01h			; ADL mode

_start:
			PUSH	AF
			PUSH	BC
			PUSH	DE
			PUSH	IX
			PUSH	IY

			LD	A, MB			; Save MB
			PUSH	AF
			XOR	A
			LD	MB, A			; Clear MB for 24-bit MOS API

			; Get system variables pointer
			LD	A, 08h			; mos_sysvars
			RST.LIL	08h			; IX = sysvars

			; Send VDU setup (mode 8, pixel coords, cursor off, CLS, CLG)
			LD	HL, setup_data
			LD	BC, 11
			RST.LIL	18h			; Send BC bytes from HL to VDP

			; Wait for mode switch to settle
			LD	B, 15
			CALL	wait_ticks

; ---- Main animation loop (infinite) ----
main_loop:
			LD	HL, frame_data + 2	; Skip num_frames u16 header
			LD	DE, 360

next_frame:
			; Read frame length: 16-bit LE at (HL)
			LD	C, (HL)
			INC	HL
			LD	B, (HL)
			INC	HL			; HL = frame VDU data start

			PUSH	DE			; save frame counter
			PUSH	HL			; save data pointer
			PUSH	BC			; save frame length

			; Send frame to VDP
			RST.LIL	18h			; HL=addr, BC=len

			; Wait 2 vsync ticks (~30fps)
			LD	B, 2
			CALL	wait_ticks

			; Check for space key (sysvar_keyascii = IX+5)
			LD	A, (IX+5)
			CP	20h			; space?
			JR	Z, _exit

			POP	BC			; restore frame length
			POP	HL			; restore data pointer
			POP	DE			; restore frame counter

			; Advance HL past frame data
			ADD	HL, BC

			; Decrement frame counter, loop if not zero
			DEC	DE
			LD	A, D
			OR	E
			JR	NZ, next_frame

			; Loop forever
			JP	main_loop

_exit:
			POP	BC			; clean up stack from frame loop
			POP	HL
			POP	DE

			; Restore mode 0 + cursor
			LD	HL, restore_data
			LD	BC, 5
			RST.LIL	18h

			POP	AF
			LD	MB, A			; Restore MB
			POP	IY
			POP	IX
			POP	DE
			POP	BC
			POP	AF
			RET

; ---- Subroutine: wait B ticks of sysvar_time ----
; sysvar_time (IX+0) increments by 2 every VBLANK (~60Hz).
; We wait for B changes of the low byte.
wait_ticks:
wt_outer:
			LD	A, (IX+0)		; current sysvar_time low byte
			LD	C, A			; snapshot
wt_inner:
			LD	A, (IX+0)		; re-read
			CP	C			; changed?
			JR	Z, wt_inner		; no — keep spinning
			DJNZ	wt_outer		; yes — one tick done
			RET

; ---- Data ----
setup_data:
			INCBIN	"cube_setup.bin"

restore_data:
			DB	22, 0			; VDU 22, 0 — mode 0
			DB	23, 1, 1		; cursor on

frame_data:
			INCBIN	"cube_frames.bin"
